### ISSUE TITLE
How can I get it work on Windows? 

### ISSUE THREAD

**Issue by Henry-T** [denglf/FormatLua#1]
How can I get it work on Windows?  Thanks !

**Comment by denglf** [comment]
I'm sorry I did not test in the windows system, and I had no windows system.

If you want to use the function to format Lua, you can use Lua Development Tools.

http://www.eclipse.org/koneki/ldt/

Good Luck!

**Comment by Henry-T** [comment]
That's fine. 
I tried to replace the lua binary with lua52.exe on windows but with no luck.

**Comment by rexdf** [comment]
#5
